### ISSUE TITLE
Issue generating documentation 

### ISSUE THREAD

**Issue by mdpradeep** [MichaelHatherly/Lapidary.jl#20]
I am trying to generate documentation from the source files. From what I understand all that I need to do is to call makedocs(). However, I get the following error when I invoke the above API.

              _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0-dev+2440 (2016-02-01 02:22 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 2bb94d6 (8 days old master)
|__/                   |  x86_64-apple-darwin13.4.0

julia> using Lapidary

julia> makedocs()
ERROR: MethodError: `cd` has no method matching cd(::Lapidary.##19#20{ASCIIString,ASCIIString,ASCIIString,Bool,Array{Tuple{Lapidary.AbstractAction,Lapidary.AbstractAction,Lapidary.AbstractAction,Vararg{Lapidary.AbstractAction}},1}}, ::Void)
Closest candidates are:
  cd(::Function)
  cd(::Function, ::AbstractString)
 in eval(Core.#eval, Module, Any) at /Applications/Julia-0.5.0-dev-2bb94d6f99.app/Contents/Resources/julia/lib/julia/sys.dylib:-1

julia> 

Am I missing something here ?

**Comment by MichaelHatherly** [comment]
The `makedocs` function is designed to be run from a file (the `docs/build.jl` file) rather than the REPL at the moment. `Base.source_dir` returns `nothing` when run from the REPL which is the problem here. One possible solution would be to use `pwd` when `source_dir === nothing`.

**Comment by mdpradeep** [comment]
I created a docs/build.jl file and ran  julia docs/build.jl. It created the build folder, css and a js file. But there is no .md file created. I was trying this for [MySQL](https://github.com/JuliaDB/MySQL.jl) package. Here's a sample of the code comments in one of the files ...

"""
Initializes the MYSQL object. Must be called before mysql_real_connect.
Memory allocated by mysql_init can be freed with mysql_close.
"""
function mysql_init(mysqlptr::Ptr{Void})
    return ccall((:mysql_init, mysql_lib),
                 Ptr{Void},
                 (Ptr{Cuchar}, ),
                 mysqlptr)
end

**Comment by MichaelHatherly** [comment]
Have you followed the same structure as this repo's `docs` folder? Do you have a `docs/src` folder containing `.md` files that are used as templates? For example:

A `docs/src/functions.md` files containing

```markdown
These are the docs for the MySQL package.

    {docs}
    mysql_init

...
```

should generate a `docs/build/functions.md` file containing something like

```markdown
These are the docs for the MySQL package

<a id='MySQL.mysql_init-1'></a>
<a href='#MySQL.mysql_init-1'> # </a>**Function**

Initializes the MYSQL object. Must be called before mysql_real_connect.
Memory allocated by mysql_init can be freed with mysql_close.

...
```

Your `build.jl` file must also import `MySQL` for this to work, so something like

```julia
using Lapidary, MySQL

makedocs()
```

If `mysql_init` is not exported then you need to qualify it in the `{docs}` block with `MySQL.mysql_init`.

Hopefully that helps. Is there a public branch containing what you've tried so far? That might be easier for me to work out what the problem is if you've already done the steps above.

**Comment by mdpradeep** [comment]
Got it. I had missed the docs/src/functions.md. Thanks.
