### ISSUE TITLE
Index for the current file

### ISSUE THREAD

**Issue by tshort** [MichaelHatherly/Lapidary.jl#22]
Is it possible to get an index for the current file? I've tried it a couple of ways:

* https://github.com/tshort/DataFrames.jl/blob/master/docs/src/lib/manipulation.md
* https://github.com/tshort/DataFrames.jl/blob/master/docs/src/lib/maintypes.md

Because the list of docstrings listed isn't in the contents on the left (they aren't headings), I'd like to put an index at the top of the current file.

**Comment by MichaelHatherly** [comment]
Doing that should work fine I think. The path is relative to the pwd. Also the two blocks, `{index}` and `{docs}`, need to be distinct. When using indented code blocks consecutive ones will merge together if there's no other content, such as a paragraph, between them. You can get around that by adding some text between them or using fenced code blocks instead.

**Comment by tshort** [comment]
Thanks @MichaelHatherly. That was it. Missed that bit.
