### ISSUE TITLE
github_api_key is printed when there is an error in deploying

### ISSUE THREAD

**Issue by randy3k** [MichaelHatherly/Lapidary.jl#24]
I believe there is a potential security concern: when there are any problems in deploying the docs, it is possible that the key `github_api_key` is printed when the remote address is echoed. It may be necessary to catch any possible errors in the function `deploydocs` by using `try`.

**Comment by MichaelHatherly** [comment]
Thanks for picking this up, much appreciated.

It may be safe enough to use `success`, since it doesn't echo anything I believe, rather than `run` for the commands that could potentially leak the key and then just display a generic error message when failures occur with those specific commands.

**Comment by MichaelHatherly** [comment]
fa72e86604fa07026110f58705be3a3075f088ca replaces some `run` calls with `success`. If there's still a way to get around those then I guess it'll need wrapping in `try`. I'd like to avoid that if possible though.

**Comment by randy3k** [comment]
@MichaelHatherly Thanks for the quick fix. I also believe that it would work.
