### ISSUE TITLE
Tables

### ISSUE THREAD

**Issue by tshort** [MichaelHatherly/Lapidary.jl#27]
I can't manage to get tables to work right:

- Source: https://github.com/tshort/Maker.jl/blob/master/docs/src/terminology.md
- Result: https://tshort.github.io/Maker.jl/stable/terminology/

I've tried various indenting approaches and use of pipes.

**Comment by MichaelHatherly** [comment]
I don't think the markdown parser currently supports block elements, like tables or code blocks, within lists, unfortunately. Unindenting the table so that it's a  toplevel element is the only workaround currently I think.

**Comment by tshort** [comment]
I thought I'd tried that. I'll try again.

**Comment by tshort** [comment]
Unindenting didn't work unless I added content between the list and the table. Adding a `&nbsp;` worked fine.

**Comment by MichaelHatherly** [comment]
You can also add two newlines before the table instead of `&nbsp;` is seems.
