### ISSUE TITLE
Output of REPL doctest

### ISSUE THREAD

**Issue by bicycle1885** [MichaelHatherly/Lapidary.jl#28]
The following case fails to pass REPL doctest:

```julia
julia> for (i, nt) in enumerate("ATNGNNT")
           if nt == 'N'
               println("N in position ", i)
           end
       end
N in position 3
N in position 5
N in position 6

```

This would be because Lapidary.jl doesn't support capturing output to `STDOUT` stream. Is that possible to support testing output?

**Comment by MichaelHatherly** [comment]
Yes, we're currently not capturing `STD*` streams. I think it should be possible though.

**Comment by MichaelHatherly** [comment]
https://github.com/MichaelHatherly/Lapidary.jl/commit/49f212e28663db028af4279efd79afbf02529ade adds `STDOUT` and `STDERR` redirection, so you should be able to use those in doctests now. Let me know if you hit any problems.
