### ISSUE TITLE
Adding image files to build.

### ISSUE THREAD

**Issue by Ward9250** [MichaelHatherly/Lapidary.jl#30]
Hi 

I'm trying to include a logo for use with material-mkdocs in my documentation. I had assumed that as long as I put it in docs/src/assets/images (because I know Lapidary puts such a directory in the build (i.e. docs/build/assets/images) lapidary would include it. However Lapidary does not do this, it simply creates docs/build/assets/*two favicon files here*. Can I direct Lapidary to include files in the build? Or do I have to manually do this in the make.jl file after calling makedocs()?

Thanks,
Ben.

**Comment by MichaelHatherly** [comment]
The `build/assets` directory is only for use by Lapidary itself, so if you have a `src/assets` folder with some contents it will get copied over to `build/assets` but then replaced by Lapidary's own `assets` folder. This should be made more obvious in the output and docs.

What you should be able to do is call your "assets" directory something like `src/resources` instead.

**Comment by Ward9250** [comment]
What is the reason for having separate assets for Lapidary and the other assets? In mkdocs I don't see anything where it needs the assets folder except for the extra_css where it uses assets/Lapidary.css. As long as people don't overwrite or call something the same name as Lapidary.css or the favicon files, shouldn't it be ok to put stuff in assets? I've seen many web design people use an assets folder for their sites, hence why I tripped up here. Anything that absolutely should be only for Lapidary and not touched might be better in a more specifically named folder?

**Comment by MichaelHatherly** [comment]
Yeah, there's no particular reason for it. I'll sort it out later tonight.

**Comment by MichaelHatherly** [comment]
82aa5d50719115b899f944db376eecd79764c4f2 allows for content in `src/assets` to be copied to `build/assets` without being overwritten. @Ward9250, does that suitably resolve this issue for you?
