### ISSUE TITLE
Duplicate headers

### ISSUE THREAD

**Issue by tshort** [MichaelHatherly/Lapidary.jl#31]
I'm getting the following with `makedocs`:

```
LoadError: duplicate header id 'deprecations' 
```

https://github.com/JuliaStats/DataFrames.jl/blob/master/NEWS.md

For some files, it's common to have multiple headings with the same name.

**Comment by MichaelHatherly** [comment]
Apologies for the slow response, was out. I've got some refactoring that needs to be pushed once I've updated docs and checked for regressions, but I believe that this is fixed with that. Probably should be sometime tomorrow or Monday I think.

**Comment by MichaelHatherly** [comment]
The refactor was 36d09ffb376c5510357c31d24a59191f0c9c9f39, which includes support for duplicate headers. It's undocumented currently, but this is basically how it works:

A document can have any number of headers with the same name and no warnings will be raised so long as none of them are referenced in a `{ref}`. If you do want to refer to a particular one of the duplicate headers then use the following `{ref#...}` syntax:

```markdown

# Header

[The custom header name]({ref#custom-name})...

## Header

# [Header]({ref#custom-name})
```

The link that wraps the third header gets removed from the final output.

This approach seems to work alright, let me know if you run into trouble.

**Comment by tshort** [comment]
Thanks!
