### ISSUE TITLE
Docstrings for all Lapidary methods/types

### ISSUE THREAD

**Issue by hayd** [MichaelHatherly/Lapidary.jl#6]
That way some interesting documentation can be generated!

**Comment by MichaelHatherly** [comment]
Do you mean all docs for a particular `Function` or every docstring from a module?

**Comment by hayd** [comment]
Ah, just functions. Sorry!

**Comment by MichaelHatherly** [comment]
Yeah, that would be good to have support for.

**Comment by hayd** [comment]
Just to clarify, as this issue was kind of vague in retrospect: I meant Lapidary functions/types should all have docstrings. :)

**Comment by MichaelHatherly** [comment]
Oh, I see now. Yup, planning to add some. A documentation package without documentation is a bit self-defeating...

**Comment by MichaelHatherly** [comment]
Most of the important functions/types are documented and added to the generated docs, closing.
